disabled_rules: # rule identifiers to exclude from running
  - identifier_name
opt_in_rules: # some rules are only opt-in
  - implicit_return
  # - empty_count
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - QuantiBase
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - fastlane

#custom override, in future this override should be deleted
line_length: 
  warning: 200
  error: 250
  ignores_comments: true
  ignores_function_declarations: true