language: objective-c
osx_image: xcode11
env:
  global: 
before_install:
- bundle update
script:
- xcodebuild -version
- xcodebuild -showsdks
- fastlane env
- fastlane test

notifications:
  slack:
    secure: RVLaDvrYmgAGYGWvWD55Vr7qR7bxxzRtPyZSPqMbcI/rnpozJAi8w31JL8Dn8DzHoaTdOU5JbhwzXItg8yLEATpjD8700d1jS9swf3FKbA+UXfCe1x/KxIp5znR1M0uGOExFGT+LRucEZA79aFAzqiMYEtT+o+HFwTC+GbGylWwpCH3zcBPqxjgy29LAsqkloYlRi6q6xV3BWYiWLR5THjkFArevunzx44cgQku36ZdtsNoeAW7lsJWaWYvjGY2c8vXe1o8Ujnzixh556nE61/PpyZ4oNK47+USV1vFZmO/mGT8B9ywHh3hjn0X/e6RhzIHkuNE+VvynpyvK1ebEhtz4Wu0334TJcToNNZ8cIILTexMZ+omtJB20rargmrKagCxfCSxOkLNuL0zAL7lDhhLTFQK9pjTdgYrRuqBP10ul385ugAPreS0utRYLTBMGjmqnNZt73WpfxcASPtr16ABJG6W399gI8NY9XrJR3iSZ8YC8glCSY5xtWuV+CzwJ+zRJKh8MavfHuRbA3iUOpGUh5k32Yuiy0hjsnmTF1x5S59TrdsRY7I8j8tObfOz2vYlYAUpDqV9b6JhOSu4RWqb0LH5WTtOs1hSPM8IPXF/nFblt/TpTlzBXoB8AHXgel/WPVqBrUgug2E3oD32bpHwKlobIRBndthUX5EhCvxo=
